version: "3.9"
services:
  backend:
    build: ./backend
    container_name: flowforge_backend
    volumes:
      - ./backend:/app
    env_file:
      - .env.backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  frontend:
    build: ./frontend
    container_name: flowforge_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
  db:
    image: postgres:15
    container_name: flowforge_db
    environment:
      POSTGRES_USER: flowforge
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: flowforge
    ports:
      - "5433:5432"
  redis:
    image: redis:7
    container_name: flowforge_redis
    ports:
      - "6379:6379"
