"""add_employee_and_crm_tables

Revision ID: e6c0eef2bc11
Revises: 20240702_02
Create Date: 2026-07-10 12:54:59.484597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c0eef2bc11'
down_revision = '20240702_02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_leads_email'), 'crm_leads', ['email'], unique=True)
    op.create_index(op.f('ix_crm_leads_id'), 'crm_leads', ['id'], unique=False)
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('job_title', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('hire_date', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'hire_date')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'job_title')
    op.drop_column('users', 'department')
    op.drop_index(op.f('ix_crm_leads_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_email'), table_name='crm_leads')
    op.drop_table('crm_leads')
    # ### end Alembic commands ###
